export const iconChars = {
    ban: '\uF05E',
    'caret-down': '\uF0D7',
    'caret-right': '\uF0DA',
    download: '\uF019',
    edit: '\uF044',
    envelope: '\uF0E0',
    'exclamation-triangle': '\uF071',
    'id-card': '\uF2C2',
    list: '\uF03A',
    lock: '\uF023',
    microphone: '\uF130',
    'phone-alt': '\uF879',
    plus: '\uF067',
    'question-circle': '\uF059',
    'sign-out-alt': '\uF2F5',
    times: '\uF00D',
    'trash-alt': '\uF2ED',
    upload: '\uF093',
    user: '\uF007'
};
